name: Gopher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ship_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Build To Nanode Via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.THEHOST }}
          username: ${{ secrets.THEUSER }}
          port: ${{ secrets.THEPORT }}
          key: ${{ secrets.THEKEY }}
          source: "/home/runner/work/gopherhole/gopherhole/target/release/gopherhole"
          target: "/var/gopher"
      
