name: Gopher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ship_it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Copy Build To Nanode Via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.THEHOST }}
          username: ${{ secrets.THEUSER }}
          password: ${{ secrets.THEPASSWORD }}
          port: ${{ secrets.THEPORT }}
          source: "/home/runner/work/gopherhole/gopherhole"
          target: "/var/gopher"
